gText_PlayerReceivedOwnItem::
    .string "{PLAYER} received one {STR_VAR_2}!$"

gText_PlayerReceivedBag::
    .string "{PLAYER} received a BAG!$"

gText_PlayerReceivedRunningShoes::
    .string "{PLAYER} received a pair of\n"
    .string "RUNNING SHOES!$"

gText_PlayerFoundPlayersItem::
    .string "{PLAYER} found {STR_VAR_1}'s\n"
    .string "{STR_VAR_2}!$"

gText_PlayerFoundArchipelagoItem::
    .string "{PLAYER} found an ARCHIPELAGO ITEM!$"
